<div class="tab-pane " id="step4" >
  <div class="row" >
    <div class="col-md-12 col-xs-12">
      <div class="portlet light select-patient-portlet prescribe-portlets">
        <div class="portlet-title">
          <div class="caption">
            <span class="caption-subject bold font-blue-hoki uppercase">Reports</span>
            <span class="caption-helper">Download Reports Generated by Prescription</span>
          </div>

          <div class="action form-inline pull-right">

          </div>
        </div>
        <div class="portlet-body">
          <div class="row">
            <div class="col-md-12">
              <!-- BEGIN PROFILE SIDEBAR -->
              <div class="profile-sidebar">
                <!-- PORTLET MAIN -->
                <div class="portlet light profile-sidebar-portlet ">
                  <!-- SIDEBAR USERPIC -->
                  <div class="profile-userpic" id="imageSection3">
                  </div>
                  <!-- END SIDEBAR USERPIC -->
                  <!-- SIDEBAR USER TITLE -->
                  <div class="profile-usertitle">
                    <div class="profile-usertitle-name"> @{{selectedPatient.fname}}
                      @{{selectedPatient.lname}} </div>
                      <div class="profile-usertitle-name" style="
                      word-wrap: break-word; font-size:15px;">
                      @{{selectedPatient.email}}</div>
                    </div>
                    <!-- END SIDEBAR USER TITLE -->
                    <!-- SIDEBAR BUTTONS -->

                    <!-- END SIDEBAR BUTTONS -->
                    <!-- SIDEBAR MENU -->

                  </div>
                  <!-- END PORTLET MAIN -->
                  <!-- PORTLET MAIN -->

                  <!-- END PORTLET MAIN -->
                </div>
                <!-- END BEGIN PROFILE SIDEBAR -->
                <!-- BEGIN PROFILE CONTENT -->
                <div class="profile-content">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="row">
                        <div class="col-md-5  ">

                          <span class="caption-subject font-blue-hoki sbold ">Time Generated :</span>
                          <label id="currentTime" style="text-decoration: underline;">02:03:35 pm</label>

                        </div>
                      </div>
                      <div class="row" >
                        <div class="col-md-12">

                          <div class="form-group row"  style="margin-left:0px;">

                            <label class="caption-subject font-blue-hoki sbold ">Comment:</label>
                            <div>
                              <textarea id="finalComment"  rows="5"  class="form-control "  style="margin-top:5px;width:100%;" placeholder="Comment"></textarea>

                            </div>
                          </div>


                        </div>
                      </div>
                      <div class="mt-element-list" style=" padding-top:10px;">
                        <div class="mt-list-head list-simple font-white bg-blue-hoki">
                          <div class="list-head-title-container">
                            <h4 class="list-title">Generated Reports</h4>
                          </div>
                        </div>
                        <div class="mt-list-container list-simple">
                          <ul>

                            <li class="mt-list-item">
                              <div class="row">
                                <div class="col-md-4 list-item-content">
                                  <h5 >
                                    <a herf="">
                                      <i class="fa fa-file-pdf-o font-red"></i> Legend  List
                                    </a>
                                  </h5>
                                </div>
                                <div class="col-md-4 list-icon-container pull-right">
                                  <a href="<?= asset('assets/images/patients/legend.pdf') ?>" target="_blank" download> <!--ng-click="genLegend()"-->
                                    <button class="btn blue-hoki btn-outline btn-file" >Download </button>
                                  </a>
                                </div>
                              </div>
                            </li>
                            <li class="mt-list-item">
                              <div class="row">
                                <div class="col-md-4 list-item-content">
                                  <h5>
                                    <a herf="">
                                      <i class="fa fa-file-pdf-o font-red"></i> Shopping List
                                    </a>
                                  </h5>
                                </div>
                                <div class="col-md-4 list-icon-container pull-right">
                                  <a herf="#" ng-click="downloadfile('ShoppingList')">
                                    <button class="btn blue-hoki btn-outline btn-file">Download </button>
                                  </a>
                                </div>
                              </div>
                            </li>
                            <li class="mt-list-item">
                              <div class="row">
                                <div class="col-md-4 list-item-content">
                                  <h5>
                                    <a herf="">
                                      <i class="fa fa-file-pdf-o font-red"></i> Recipes List</a>
                                    </h5>
                                  </div>
                                  <div class="col-md-4 list-icon-container pull-right">
                                    <a herf="#" ng-click="downloadfile('RecipeList')">
                                      <button class="btn blue-hoki btn-outline btn-file">Download </button>
                                    </a>
                                  </div>
                                </div>
                              </li>
                              <li class="mt-list-item">
                                <div class="row">
                                  <div class="col-md-6 list-item-content">
                                    <h5>
                                      <a herf="">
                                        <i class="fa fa-file-pdf-o font-red"></i> Comprehensive  List
                                      </a>
                                    </h5>
                                  </div>
                                  <div class="col-md-4 list-icon-container pull-right">
                                    <a herf="#" ng-click="downloadfile('ComprehensiveList')">
                                      <button class="btn blue-hoki btn-outline btn-file">Download</button>
                                    </a>
                                  </a>
                                </div>
                              </div>
                            </li>

                          </ul>
                        </div>
                      </div>

                      <div class="col-md-12 ">
                        <a href="<?= asset('assets/images/patients/legend.pdf') ?>" target="_blank" download ng-click="downloadfile('ShoppingList'); downloadfile('RecipeList'); downloadfile('ComprehensiveList')  ">
                          <button class="btn blue-hoki btn-file pull-right" style="margin-top: 10px; margin-bottom: 10px;" id="download-all-btn">Download All</button>
                        </a>
                        <!-- END PORTLET -->
                      </div>
                      <!-- END PROFILE CONTENT -->
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
    <div class="row step-buttons" style="margin-top:20px;">
      <div class="col-md-12 col-sm-12">
        <a  href="#step1" data-toggle="tab" ng-click="editNewPrescription(); intializeTabSetps()" class="btn btn-sm yellow pull-left tab-change">Edit Prescription</a>
        <!-- <a  href="#step3" data-toggle="tab" class="btn yellow pull-left tab-change" >Back</a> -->
        <a href="http://diet.invictuszone.com/user/prescribe">
          <button class="btn btn-sm green-haze pull-right" id="add-another-btn">Another Patient</button>

        </a>
      </div>
    </div>
  </div>
